### ISSUE TITLE
[Settings] cross-env 도입

### ISSUE THREAD

**Issue by ChoHadam** [A-fume/A.fume.Server#143]
## 도입 배경
테스트 코드를 실행하기 위한 스크립트에 환경변수를 넣어서 설정하도록 하는 과정에서, 윈도우에서는 리눅스와 다른 방법으로 설정해야함을 알게되었습니다.
```
"scripts": {
    // linux
    "test": "NODE_ENV=test mocha" // linux

    // windows
    "test": "set NODE_ENV=test&&mocha"  // windows
  },
```
운영체제별로 환경변수를 설정하는 법이 다르기 때문에, 어떤 운영체제에서든지 같은 스크립트로 실행 가능하게끔 cross-env를 도입했습니다. 
```
"scripts": {
    "test": "cross-env NODE_ENV=test mocha"
  },
```

## 모듈 정의
[cross-env](https://www.npmjs.com/package/cross-env) 모듈은 프로젝트 참여자 각각이 MacOS, Windows, Linux 등 다양한 OS 마다 환경변수를 설정하는 방법이 다르기 때문에 이것에 대한 대책을 마련한 모듈입니다.

**Comment by heesung6701** [comment]
👍🏽
