### ISSUE TITLE
[BUG] 로그인시 500 에러 발생

### ISSUE THREAD

**Issue by ChoHadam** [A-fume/A.fume.Server#265]
## 버그 묘사
기존 계정으로 로그인 또는 회원가입 후 로그인시 500 에러 발생

api 호출시 콘솔에 찍힌 로그
```
0659951070f3e3896ee33bde04634e18:decf91ea
f83dce115ecf72fedc93ea0623322318:f5bf6eaf
error: undefined {"timestamp":"2022-04-05 03:09:24"}
POST /A.fume/api/0.0.1/user/login 500 65.511 ms - -
```
## 스크린샷
![image](https://user-images.githubusercontent.com/35447878/161605662-9b1c238e-e26b-417a-b318-9eb10bad2368.png)

**Comment by heesung6701** [comment]
아래 내용에 대해서도 추가 확인 부탁드립니다!
1. 향수 조회 api 는 동작하는가
2. RDS에 연결이 정상적으로 되는가 (RDS 보안그룹에서 IP 등록해야 접속 가능함)
3. 콘솔에 찍힌 로그 말고 debug 로그로 공유 부탁드립니다.

**Comment by heesung6701** [comment]
@ChoHadam 확인하고 해결 되었으면 close 해주세요
