### ISSUE TITLE
[BUG] 향수 검색 기능 : 예상과 다른 검색 결과

### ISSUE THREAD

**Issue by ChoHadam** [A-fume/A.fume.Server#343]
## summary
검색창에 키워드 입력시, 향수명에 해당 키워드가 포함되거나 일치하는 향수가 검색되어야하는데 빈 리스트를 리턴한다.
따라서, 향수명에 키워드가 포함되거나 향수명이 키워드와 일치하는 향수 목록을 리턴하도록 수정해야한다.

## 관련 Endpoint
GET /perfume/search

## 버그 재현 경로
- [ALWAYS] 'gu' 입력시 빈 리스트 리턴
```
Requst body

{
  "searchText": "gu",
  "keywordList": [
      0
  ],
  "ingredientList": [
      0
  ],
  "brandList": [
      0
  ]
}
```
```
Response body

{
  "message": "향수 검색 조회 성공",
  "data": {
    "count": 0,
    "rows": []
  }
}
```
- [ALWAYS] 'Gucci Bloom Acqua di Fiori Eau de Toillette' 입력시 빈 리스트 리턴
```
Requst body

{
  "searchText": "Gucci Bloom Acqua di Fiori Eau de Toillette",
  "keywordList": [
    0
  ],
  "ingredientList": [
    0
  ],
  "brandList": [
    0
  ]
}
```
```
Response body

{
  "message": "향수 검색 조회 성공",
  "data": {
    "count": 0,
    "rows": []
  }
}
```
## 스크린샷
<img width="1470" alt="스크린샷 2022-08-28 오전 11 53 12" src="https://user-images.githubusercontent.com/35447878/187055379-4aa5999d-27ff-4639-b5ed-01b9e60594db.png">

<img width="1408" alt="스크린샷 2022-08-28 오전 11 52 11" src="https://user-images.githubusercontent.com/35447878/187055387-edd5193c-ee56-42b2-af99-c04bf8c3732a.png">

**Comment by heesung6701** [comment]
#288 와 동일한 이슈로 보입니다.
