### ISSUE TITLE
[BUG] Perfume 검색 기능 Interner Server Error

### ISSUE THREAD

**Issue by ChoHadam** [A-fume/A.fume.Server#358]
## summary
production-2 서버에서 향수 검색시 Interner Server Error 발생합니다. 
영어/한국어 키워드 모두 작동하지 않습니다.
FullTEXT Index가 제대로 적용되지 않은듯 합니다.

## 관련 Endpoint
GET /perfume/search

## 스크린샷
<img width="1413" alt="스크린샷 2022-08-30 오후 12 59 13" src="https://user-images.githubusercontent.com/35447878/187346099-6cd22426-53e2-40ce-aeef-9401e10f30e2.png">

<img width="773" alt="스크린샷 2022-08-30 오후 12 54 19" src="https://user-images.githubusercontent.com/35447878/187346043-e67ea4e9-96ca-4b6f-bc47-3efab02fe944.png">

**Comment by ChoHadam** [comment]
@heesung6701 
Dev 브랜치에서 로컬로 돌리면, 
에러는 뜨지 않으나 항상 검색 결과가 빈 리스트를 리턴합니다. 
이 부분도 확인 부탁드립니다!

**Comment by ChoHadam** [comment]
name, englishName에 FullTEXT Index 걸려있지 않아서 
기존에 name에만 걸려있던 단일 인덱스 `ft_idx_perfume_name_one`를 제거하고 
name, englishName 두 컬럼에 복합 인덱스 `ft_idx_perfume_name`를 추가했습니다.

```
DROP INDEX ft_idx_perfume_name_one ON perfumes;
DROP INDEX ft_idx_brand_name_one ON brands;
CREATE FULLTEXT INDEX ft_idx_perfume_name ON perfumes(`name`, `english_name`);
CREATE FULLTEXT INDEX ft_idx_brand_name ON brands(`name`, `english_name`);
```

그 결과, prd-server에서 Perfume 검색시 Interner Server Error는 발생하지 않지만,
검색 결과가 항상 빈리스트를 리턴합니다. 
확인 부탁드립니다. 
@heesung6701

**Comment by heesung6701** [comment]
> 검색 결과가 항상 빈리스트를 리턴합니다.
> 확인 부탁드립니다.
@ChoHadam 
검색어에 따라서 빈 배열이 가고 아닌 경우가 있네요. 
이 부분은 FULL TEXT에 따른 검색결과가 다른거라 해당 로직에 대해서 확인 해봐야 할 거 같습니다,,

**Comment by heesung6701** [comment]
2 글자 이하인 경우는 불용어로 잡아서 검색이 안되고 있으며
Tom 같은 경우는 데이터가 존재하지 않아서 빈 배열로 나오고 있습니다.
