### ISSUE TITLE
[BUG] 지속력 보통 api 변경 (normal -> medium)

### ISSUE THREAD

**Issue by heesung6701** [A-fume/A.fume.Server#402]
## summary

지속력에서 보통에 해당  하는 정보를 normal -> medium으로 변경

## 관련 Endpoint

/perfume/{perfumdIdx}

## 버그 재현 경로

문서상 응답
```
    "longevity": {
      "veryWeak": 100,
      "weak": 100,
      "medium": 100,
      "strong": 100,
      "veryStrong": 100
    },
```

실제 응답
```
    "longevity": {
      "veryWeak": 20,
      "weak": 20,
      "normal": 20,
      "strong": 20,
      "veryStrong": 20
    },
```

## 필요한 작업

```
data class Longevity(
    val veryWeak: Int,
    val weak: Int,
    val medium: Int,
    val strong: Int,
    val veryStrong : Int,
    val undefined: Int
)
```

**Comment by ChoHadam** [comment]
🙋🏻‍♀️ 이슈 내용이 이해가 잘 안되는 부분이 있는데, 단순히 medium -> normal로 용어를 바꾼건가요? 바꾸게된 이유는 무엇인가요?

**Comment by heesung6701** [comment]
@ChoHadam swagger문서 보면 definition이 medium 으로 되어 있습니다...
버그이죠...
현재 클라이언트 측에서 medium으로 받도록 이미 구현하였고 앱도 출시된 상태로 서버측 컨트롤러 계층만 수정 했습니다.

**Comment by ChoHadam** [comment]
@heesung6701 아하 이해했습니다! 버그 수정뿐만 아니라 다른 부분들도 고치신 것 같아서 확인차 여쭤봤습니다.

**Comment by heesung6701** [comment]
아아 다른 부분이 테스트 코드 말한거였군요! 버그 수정 할때 테스트 코드 먼저 작성하도록 시도 하고 있어요 :)
