### ISSUE TITLE
[Feature] 비밀번호 확인 엔드포인트 추가

### ISSUE THREAD

**Issue by heesung6701** [A-fume/A.fume.Server#423]
## 기능 정의

비밀번호 변경 화면 내 현재 비밀번호 검증을 위한 엔드포인트 필요

## 작업 내용

엔드포인트 추가

**Comment by ChoHadam** [comment]
@heesung6701 해당 issue 관련 코드 main에 merged 되었는데 issue 닫아도 될까요? close 키워드 쓰셨는데 자동으로 안 닫힌것 같습니다!
