### ISSUE TITLE
[BUG] Error: process.env.NODE_ENV is unknown.

### ISSUE THREAD

**Issue by ChoHadam** [A-fume/A.fume.Server#462]
## summary
`.env`(환경변수파일) 파일을 profile에 따라 개별 파일로 분리하는 작업을 진행하던 중,
기존의 `.env` 파일을 제거하고 `npm start` 명령어를 실행했더니 
`process.env.NODE_ENV`를 호출하는 곳에서 발생한 에러입니다.

```
// package.json 코드 일부분

{
	"scripts": {
		"start": "cross-env NODE_ENV=development REDIS_DB_ID=1 npm run build && node ./dist/bin/www ",
	}
}
```
`npm script`로 등록한 환경변수가 정상적으로 주입되지 않았기 때문에 발생한것으로 보입니다.

Run `npm script` with `cross-env` and `&&` not working properly.

## 필요한 작업
- Fix some npm scripts.

**Comment by heesung6701** [comment]
리눅스 커맨드 && 이전에 선언한 환경 변수는 && 이후에 영향을 끼치지 않습니다.
따라서 기존 커맨드에서 설정한  NODE_ENV는 node 커맨드 수행시 적용되지 않습니다.
이는 리눅스 && operator의 의도된 동작입니다.

```
cross-env NODE_ENV=development REDIS_DB_ID=1 npm run build && node ./dist/bin/www 
```

cross-env에 커맨드를 "" 로 감싸면 하나의 커맨드로 인식되어서 모든 명령어에 환경 변수를 적용시킬 수 있습니다.
